apiVersion: networking.istio.io/v1alpha3
kind: VirtualService=
metadata:
  name: vs-grafana
  namespace: monitoring
spec:
  hosts:
  - grafana.example.com
  gateways:
  - istion-ingress/gateway # this is refering the app-gateway created inside istio-system namespace
  http:
  - route:
    - destination:
        host: grafana
        port:
          number: 80
